# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Update web app (backend & frontend) docker image for my portfolio

on:
  push:
    branches:
    - main
    paths:
      - src/main/**
      - .github/workflows/**

jobs:
  deploy:
    runs-on: portfolio-web
    steps:
    - name: Clean the repo
      run: rm -rf spring-web-portfolio/
      
    - name: Import Repo
      run: git clone https://github.com/smarsou/spring-web-portfolio.git

    - name: Update permissions
      run: cd spring-web-portfolio/ && chmod 777 mvnw

    - name: Build the jar file
      run: cd spring-web-portfolio/ && ./mvnw package -DskipTests

    - name: Update docker image
      run: cd spring-web-portfolio/ && sudo docker build --build-arg JAR_FILE=target/*.jar -t smarsou/web .

    - name: Clean code
      run: rm -rf spring-web-portfolio/
